-- Seed Warlock progression data based on the provided table
-- This populates the class_progressions table with Warlock-specific data

-- First, ensure the warlock class exists
INSERT INTO classes (id, name) VALUES ('warlock', 'Warlock') ON CONFLICT (id) DO NOTHING;

-- Insert Warlock progression data
-- Based on the table: Level, Proficiency Bonus, Features, Cantrips Known, Spells Known, Spell Slots, Slot Level, Invocations Known

INSERT INTO class_progressions (class_id, level, progression_type_id, value) VALUES
-- Proficiency Bonus
('warlock', 1, 'proficiency_bonus', '+2'),
('warlock', 2, 'proficiency_bonus', '+2'),
('warlock', 3, 'proficiency_bonus', '+2'),
('warlock', 4, 'proficiency_bonus', '+2'),
('warlock', 5, 'proficiency_bonus', '+3'),
('warlock', 6, 'proficiency_bonus', '+3'),
('warlock', 7, 'proficiency_bonus', '+3'),
('warlock', 8, 'proficiency_bonus', '+3'),
('warlock', 9, 'proficiency_bonus', '+4'),
('warlock', 10, 'proficiency_bonus', '+4'),
('warlock', 11, 'proficiency_bonus', '+4'),
('warlock', 12, 'proficiency_bonus', '+4'),
('warlock', 13, 'proficiency_bonus', '+5'),
('warlock', 14, 'proficiency_bonus', '+5'),
('warlock', 15, 'proficiency_bonus', '+5'),
('warlock', 16, 'proficiency_bonus', '+5'),
('warlock', 17, 'proficiency_bonus', '+6'),
('warlock', 18, 'proficiency_bonus', '+6'),
('warlock', 19, 'proficiency_bonus', '+6'),
('warlock', 20, 'proficiency_bonus', '+6'),

-- Cantrips Known
('warlock', 1, 'cantrips_known', 2),
('warlock', 2, 'cantrips_known', 2),
('warlock', 3, 'cantrips_known', 2),
('warlock', 4, 'cantrips_known', 3),
('warlock', 5, 'cantrips_known', 3),
('warlock', 6, 'cantrips_known', 3),
('warlock', 7, 'cantrips_known', 3),
('warlock', 8, 'cantrips_known', 3),
('warlock', 9, 'cantrips_known', 3),
('warlock', 10, 'cantrips_known', 4),
('warlock', 11, 'cantrips_known', 4),
('warlock', 12, 'cantrips_known', 4),
('warlock', 13, 'cantrips_known', 4),
('warlock', 14, 'cantrips_known', 4),
('warlock', 15, 'cantrips_known', 4),
('warlock', 16, 'cantrips_known', 4),
('warlock', 17, 'cantrips_known', 4),
('warlock', 18, 'cantrips_known', 4),
('warlock', 19, 'cantrips_known', 4),
('warlock', 20, 'cantrips_known', 4),

-- Spells Known
('warlock', 1, 'spells_known', 2),
('warlock', 2, 'spells_known', 3),
('warlock', 3, 'spells_known', 4),
('warlock', 4, 'spells_known', 5),
('warlock', 5, 'spells_known', 6),
('warlock', 6, 'spells_known', 7),
('warlock', 7, 'spells_known', 8),
('warlock', 8, 'spells_known', 9),
('warlock', 9, 'spells_known', 10),
('warlock', 10, 'spells_known', 10),
('warlock', 11, 'spells_known', 11),
('warlock', 12, 'spells_known', 11),
('warlock', 13, 'spells_known', 12),
('warlock', 14, 'spells_known', 12),
('warlock', 15, 'spells_known', 13),
('warlock', 16, 'spells_known', 13),
('warlock', 17, 'spells_known', 14),
('warlock', 18, 'spells_known', 14),
('warlock', 19, 'spells_known', 15),
('warlock', 20, 'spells_known', 15),

-- Spell Slots (Warlock uses Pact Magic: 2 slots that scale in level)
('warlock', 1, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 1}'),
('warlock', 2, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 1}'),
('warlock', 3, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 2}'),
('warlock', 4, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 2}'),
('warlock', 5, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 3}'),
('warlock', 6, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 3}'),
('warlock', 7, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 4}'),
('warlock', 8, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 4}'),
('warlock', 9, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 10, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 11, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 12, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 13, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 14, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 15, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 16, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 17, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 18, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 19, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),
('warlock', 20, 'spell_slots', '{"max": 2, "used": 0, "slot_level": 5}'),

-- Invocations Known
('warlock', 1, 'invocations_known', 0),
('warlock', 2, 'invocations_known', 2),
('warlock', 3, 'invocations_known', 2),
('warlock', 4, 'invocations_known', 2),
('warlock', 5, 'invocations_known', 3),
('warlock', 6, 'invocations_known', 3),
('warlock', 7, 'invocations_known', 4),
('warlock', 8, 'invocations_known', 4),
('warlock', 9, 'invocations_known', 5),
('warlock', 10, 'invocations_known', 5),
('warlock', 11, 'invocations_known', 5),
('warlock', 12, 'invocations_known', 6),
('warlock', 13, 'invocations_known', 6),
('warlock', 14, 'invocations_known', 6),
('warlock', 15, 'invocations_known', 7),
('warlock', 16, 'invocations_known', 7),
('warlock', 17, 'invocations_known', 7),
('warlock', 18, 'invocations_known', 8),
('warlock', 19, 'invocations_known', 8),
('warlock', 20, 'invocations_known', 8)
ON CONFLICT (class_id, level, progression_type_id) DO NOTHING;

-- Insert Warlock class features
INSERT INTO features (id, source_id, source_type, level_required, name, description, feature_type) VALUES
('warlock_otherworldly_patron', 'warlock', 'class', 1, 'Otherworldly Patron', 'Your patron grants you power through a pact.', 'class_feature'),
('warlock_pact_magic', 'warlock', 'class', 1, 'Pact Magic', 'You know spells that you can cast as warlock spells.', 'class_feature'),
('warlock_eldritch_invocations', 'warlock', 'class', 2, 'Eldritch Invocations', 'You gain access to invocations, powerful spells that enhance your abilities.', 'class_feature'),
('warlock_pact_boon', 'warlock', 'class', 3, 'Pact Boon', 'Your patron grants you a boon: Pact of the Tome, Pact of the Chain, or Pact of the Blade.', 'class_feature'),
('warlock_asi_4', 'warlock', 'class', 4, 'Ability Score Improvement', 'Increase one ability score by 2 or two by 1.', 'class_feature'),
('warlock_asi_8', 'warlock', 'class', 8, 'Ability Score Improvement', 'Increase one ability score by 2 or two by 1.', 'class_feature'),
('warlock_asi_12', 'warlock', 'class', 12, 'Ability Score Improvement', 'Increase one ability score by 2 or two by 1.', 'class_feature'),
('warlock_asi_16', 'warlock', 'class', 16, 'Ability Score Improvement', 'Increase one ability score by 2 or two by 1.', 'class_feature'),
('warlock_asi_19', 'warlock', 'class', 19, 'Ability Score Improvement', 'Increase one ability score by 2 or two by 1.', 'class_feature'),
('warlock_mystic_arcanum_6', 'warlock', 'class', 11, 'Mystic Arcanum (6th)', 'You gain a 6th-level warlock spell of your choice.', 'mystic_arcanum'),
('warlock_mystic_arcanum_7', 'warlock', 'class', 13, 'Mystic Arcanum (7th)', 'You gain a 7th-level warlock spell of your choice.', 'mystic_arcanum'),
('warlock_mystic_arcanum_8', 'warlock', 'class', 15, 'Mystic Arcanum (8th)', 'You gain an 8th-level warlock spell of your choice.', 'mystic_arcanum'),
('warlock_mystic_arcanum_9', 'warlock', 'class', 17, 'Mystic Arcanum (9th)', 'You gain a 9th-level warlock spell of your choice.', 'mystic_arcanum'),
('warlock_eldritch_master', 'warlock', 'class', 20, 'Eldritch Master', 'You can regain all your warlock spell slots.', 'class_feature')
ON CONFLICT (id) DO NOTHING;
